version: '3.6'
services:
  recognition:
    build:
      context: ./recognition/recognition.container
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
      - LD_LIBRARY_PATH=/opt/vc/lib
    devices:
      - "/dev/vcsm:/dev/vcsm"
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/video0:/dev/video0"
    volumes:
      - /opt/vc:/opt/vc
      - ./shared:/shared
      - ./recognition/service:/service
  messenger:
    image: arm32v7/redis
    ports: 
      - "6379:6379"
    volumes:
      - messenger_data:/data
  streaming:
    build:
      context: ./streaming/streaming.container
    depends_on:
      - messenger
      - recognition
    ports: 
      - "8000:8000"
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
    volumes:
      - ./shared:/shared
      - ./streaming/service:/service 
  publishing:
    build:
      context: ./publishing/publishing.container
    depends_on:
      - messenger
      - recognition
    ports: 
    environment:
      - MQTT_BROKER=192.168.0.80
      - MQTT_PORT=1883
    volumes:
      - ./shared:/shared
      - ./publishing/service:/service
      
volumes:
  messenger_data: