version: '3.6'
services:
  recognition:
    build:
      context: ./recognition/recognition_container
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
      - LD_LIBRARY_PATH=/opt/vc/lib
    devices:
      - "/dev/vcsm:/dev/vcsm"
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/video0:/dev/video0"
    volumes:
      - /opt/vc:/opt/vc
      - ./shared:/shared
      - ./recognition/recognition_container/service:/service
  messenger:
    image: arm32v7/redis
    ports: 
      - "6379:6379"
    volumes:
      - messenger_data:/data
  streaming:
    build:
      context: ./streaming/streaming.container
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
    volumes:
      - ./shared:/shared
      - ./streaming/service:/service
      
volumes:
  shared: 
  messenger_data: